/**
 * Cross-language UCP signing fixture corpus.
 *
 * Each fixture file is a `{ profile, jwks, alg, kid, generator }` envelope.
 * Both Node and Python check in identical fixtures here so a future
 * canonicalization change in either language fails CI loudly. Without this,
 * cross-language byte parity drift would silently break verifier-side
 * compatibility in production.
 */

import { readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { verifyUCPProfile, type JWKSResponse, type SignedUCPProfile } from '../../src/identity/ucp-jwks';

interface Fixture {
  profile: SignedUCPProfile;
  jwks: JWKSResponse;
  alg: 'EdDSA' | 'ES256';
  kid: string;
  generator: 'node' | 'python';
}

const FIXTURE_DIR = join(__dirname, '..', 'fixtures', 'cross-lang');

const fixtures: { name: string; data: Fixture }[] = readdirSync(FIXTURE_DIR)
  .filter((f) => f.endsWith('.json'))
  .map((name) => ({
    name,
    data: JSON.parse(readFileSync(join(FIXTURE_DIR, name), 'utf-8')) as Fixture,
  }));

describe('UCP signing — cross-language fixture corpus', () => {
  for (const { name, data } of fixtures) {
    it(`verifies ${name} (${data.alg}, generated by ${data.generator})`, async () => {
      const ok = await verifyUCPProfile(data.profile, data.jwks);
      expect(ok).toBe(true);
    });
  }

  it('corpus covers the canonical scenarios from both languages', () => {
    const names = fixtures.map((f) => f.name);
    const generators = new Set(fixtures.map((f) => f.data.generator));
    expect(generators).toContain('node');
    expect(generators).toContain('python');

    // Each language ships its base scenarios so cross-lang verify exercises all of them.
    // `emoji-keys` exercises non-ASCII object keys with codepoints that genuinely
    // distinguish UTF-16 first-unit sort from Unicode codepoint sort: BMP private use
    // (U+E000) ranks BEFORE supplementary plane (U+1F377) by codepoint but AFTER it by
    // UTF-16 first unit (because the high surrogate 55356 < 57344). Both repos ship the
    // node and python emoji-keys fixtures so a regression in either language's key sort
    // surfaces here.
    for (const lang of ['node', 'py'] as const) {
      for (const scenario of [
        'minimal',
        'es256-rails',
        'extras-int',
        'capability',
        'unicode',
        'multikey',
        'emoji-keys',
        'int-boundary',
        // `data-driven-claims` exercises the raw-dict fallback read path
        // (`AssessResult(raw={"account_verification": {...}})`) that production
        // callers populate. `typed-claims` exercises the typed field path
        // (`AssessResult(account_verification={...}, raw=None)`) that
        // hand-constructed callers use — Node's `buildUCPProfile` reads typed
        // fields directly without consulting raw, so both paths must produce
        // byte-identical canonical bytes across languages or cross-lang verify
        // silently drifts.
        'data-driven-claims',
        'typed-claims',
      ] as const) {
        expect(names).toContain(`${lang}-${scenario}.json`);
      }
    }
  });
});
