/**
 * Cross-language UCP signing fixture corpus.
 *
 * Each fixture file is a `{ profile, jwks, alg, kid, generator }` envelope.
 * Both Node and Python check in identical fixtures here so a future
 * canonicalization change in either language fails CI loudly. Without this,
 * cross-language byte parity drift would silently break verifier-side
 * compatibility in production.
 */

import { readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { verifyUCPProfile, type JWKSResponse, type SignedUCPProfile } from '../../src/identity/ucp-jwks';

interface Fixture {
  profile: SignedUCPProfile;
  jwks: JWKSResponse;
  alg: 'EdDSA' | 'ES256';
  kid: string;
  generator: 'node' | 'python';
}

const FIXTURE_DIR = join(__dirname, '..', 'fixtures', 'cross-lang');

const fixtures: { name: string; data: Fixture }[] = readdirSync(FIXTURE_DIR)
  .filter((f) => f.endsWith('.json'))
  .map((name) => ({
    name,
    data: JSON.parse(readFileSync(join(FIXTURE_DIR, name), 'utf-8')) as Fixture,
  }));

describe('UCP signing — cross-language fixture corpus', () => {
  for (const { name, data } of fixtures) {
    it(`verifies ${name} (${data.alg}, generated by ${data.generator})`, async () => {
      const ok = await verifyUCPProfile(data.profile, data.jwks);
      expect(ok).toBe(true);
    });
  }

  it('corpus covers the canonical scenarios from both languages', () => {
    const names = fixtures.map((f) => f.name);
    const generators = new Set(fixtures.map((f) => f.data.generator));
    expect(generators).toContain('node');
    expect(generators).toContain('python');

    // Each language ships its base scenarios so cross-lang verify exercises all of them.
    // `i18n-keys` exercises non-ASCII object keys (BMP + non-BMP); both languages must
    // sort by Unicode codepoint to maintain byte parity. Node's lang prefix is `node`,
    // python's is `py`.
    for (const lang of ['node', 'py'] as const) {
      for (const scenario of ['minimal', 'es256-rails', 'extras-int', 'capability', 'unicode', 'multikey'] as const) {
        expect(names).toContain(`${lang}-${scenario}.json`);
      }
    }
    expect(names).toContain('node-i18n-keys.json');
  });
});
