/**
 * Regenerate the full cross-lang fixture corpus (Node side).
 *
 * Writes all `node-*.json` fixtures under `tests/fixtures/cross-lang/`. Used
 * after a canonicalization-relevant change (typ rename, capability-name
 * rename, schema-URL rename, key-sort tweak, etc.) where every JWS in the
 * corpus needs to be re-signed.
 *
 * Each scenario hand-crafts the profile body, signs with a fresh keypair, and
 * writes the `{ profile, jwks, alg, kid, generator }` envelope. Cross-lang
 * verify in `tests/identity/cross-lang.test.ts` (and the python sibling)
 * pulls these in alongside the `py-*` fixtures generated by the python
 * sibling.
 */

import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { buildUCPProfile, type UCPSigningKey } from '../src/identity/ucp';
import {
  buildJWKSResponse,
  generateUCPSigningKey,
  signUCPProfile,
  type SignedUCPProfile,
} from '../src/identity/ucp-jwks';
import type { AgentScoreData } from '../src/core';

const OUT_DIR = join(__dirname, '..', 'tests', 'fixtures', 'cross-lang');

interface FixtureEnvelope {
  profile: SignedUCPProfile;
  jwks: { keys: UCPSigningKey[] };
  alg: 'EdDSA' | 'ES256';
  kid: string;
  generator: 'node';
}

function writeFixture(name: string, env: FixtureEnvelope): void {
  const out = join(OUT_DIR, `${name}.json`);
  writeFileSync(out, `${JSON.stringify(env, null, 2)}\n`);
  console.warn(`wrote ${out}`);
}

async function main(): Promise<void> {
  // -------------------------------------------------------------------------
  // node-minimal
  // -------------------------------------------------------------------------
  {
    const KID = 'node-minimal-EdDSA';
    const { privateKey, publicJWK } = await generateUCPSigningKey({ kid: KID });
    const profile = buildUCPProfile({
      name: 'Minimal Merchant',
      services: [{ type: 'rest', url: 'https://m.example.com' }],
      payment_handlers: [],
      signing_keys: [publicJWK as UCPSigningKey],
    });
    const signed = await signUCPProfile(profile, { signingKey: privateKey, kid: KID });
    writeFixture('node-minimal', {
      profile: signed,
      jwks: buildJWKSResponse([publicJWK]),
      alg: 'EdDSA',
      kid: KID,
      generator: 'node',
    });
  }

  // -------------------------------------------------------------------------
  // node-es256-rails — multi-service + multi-rail + ES256 signing key
  // -------------------------------------------------------------------------
  {
    const KID = 'node-es256-rails-ES256';
    const { privateKey, publicJWK } = await generateUCPSigningKey({ kid: KID, alg: 'ES256' });
    const profile = buildUCPProfile({
      name: 'ES256 Merchant',
      services: [
        { type: 'rest', url: 'https://a.example.com' },
        { type: 'a2a', url: 'https://a.example.com/agent-card.json' },
      ],
      payment_handlers: [
        { name: 'tempo', config: { rail: 'tempo-mainnet', chain_id: 4217 } },
        { name: 'x402', config: { networks: ['base-8453'] } },
      ],
      signing_keys: [publicJWK as UCPSigningKey],
    });
    const signed = await signUCPProfile(profile, { signingKey: privateKey, kid: KID, alg: 'ES256' });
    writeFixture('node-es256-rails', {
      profile: signed,
      jwks: buildJWKSResponse([publicJWK]),
      alg: 'ES256',
      kid: KID,
      generator: 'node',
    });
  }

  // -------------------------------------------------------------------------
  // node-extras-int — payment_handler config with int + string fields
  // -------------------------------------------------------------------------
  {
    const KID = 'node-extras-int-EdDSA';
    const { privateKey, publicJWK } = await generateUCPSigningKey({ kid: KID });
    const profile = buildUCPProfile({
      name: 'Extras Merchant',
      services: [{ type: 'rest', url: 'https://e.example.com' }],
      payment_handlers: [{ name: 'stripe', config: { profile_id: 'abc', count: 7 } }],
      signing_keys: [publicJWK as UCPSigningKey],
    });
    const signed = await signUCPProfile(profile, { signingKey: privateKey, kid: KID });
    writeFixture('node-extras-int', {
      profile: signed,
      jwks: buildJWKSResponse([publicJWK]),
      alg: 'EdDSA',
      kid: KID,
      generator: 'node',
    });
  }

  // -------------------------------------------------------------------------
  // node-capability — a hand-crafted vendor capability (renamed to
  // sh.agentscore.identity to match the new namespace; the in-fixture name is
  // independent of the SDK's auto-injection but consistency keeps the corpus
  // honest about what callers should publish).
  // -------------------------------------------------------------------------
  {
    const KID = 'node-capability-EdDSA';
    const { privateKey, publicJWK } = await generateUCPSigningKey({ kid: KID });
    const profile = buildUCPProfile({
      name: 'Capability Merchant',
      services: [{ type: 'rest', url: 'https://c.example.com' }],
      capabilities: [
        {
          name: 'sh.agentscore.identity',
          schema: 'https://agentscore.sh/schemas/ucp/sh-agentscore-identity-v1.json',
          version: '1',
          kyc_required: true,
        },
      ],
      payment_handlers: [
        { name: 'tempo', config: { rail: 'tempo-mainnet', chain_id: 4217 } },
      ],
      signing_keys: [publicJWK as UCPSigningKey],
    });
    const signed = await signUCPProfile(profile, { signingKey: privateKey, kid: KID });
    writeFixture('node-capability', {
      profile: signed,
      jwks: buildJWKSResponse([publicJWK]),
      alg: 'EdDSA',
      kid: KID,
      generator: 'node',
    });
  }

  // -------------------------------------------------------------------------
  // node-unicode — multi-byte UTF-8 in name / url / config
  // -------------------------------------------------------------------------
  {
    const KID = 'node-unicode-EdDSA';
    const { privateKey, publicJWK } = await generateUCPSigningKey({ kid: KID });
    const profile = buildUCPProfile({
      name: 'Café 日本 🍷 Merchant',
      services: [{ type: 'rest', url: 'https://日本.example.com' }],
      payment_handlers: [{ name: 'tempo', config: { note: 'メモ' } }],
      signing_keys: [publicJWK as UCPSigningKey],
    });
    const signed = await signUCPProfile(profile, { signingKey: privateKey, kid: KID });
    writeFixture('node-unicode', {
      profile: signed,
      jwks: buildJWKSResponse([publicJWK]),
      alg: 'EdDSA',
      kid: KID,
      generator: 'node',
    });
  }

  // -------------------------------------------------------------------------
  // node-multikey — JWKS with two keys, signed by the newer one
  // -------------------------------------------------------------------------
  {
    const oldKey = await generateUCPSigningKey({ kid: 'node-multikey-old' });
    const newKey = await generateUCPSigningKey({ kid: 'node-multikey-new' });
    const profile = buildUCPProfile({
      name: 'Multi-Key Merchant',
      services: [{ type: 'rest', url: 'https://mk.example.com' }],
      payment_handlers: [{ name: 'tempo', config: { rail: 'tempo-mainnet' } }],
      signing_keys: [oldKey.publicJWK as UCPSigningKey, newKey.publicJWK as UCPSigningKey],
    });
    const signed = await signUCPProfile(profile, { signingKey: newKey.privateKey, kid: 'node-multikey-new' });
    writeFixture('node-multikey', {
      profile: signed,
      jwks: buildJWKSResponse([oldKey.publicJWK, newKey.publicJWK]),
      alg: 'EdDSA',
      kid: 'node-multikey-new',
      generator: 'node',
    });
  }

  // -------------------------------------------------------------------------
  // node-emoji-keys — extras with non-ASCII object keys (BMP private use, CJK
  // compatibility, supplementary plane). Exercises codepoint-vs-UTF-16 sort.
  // -------------------------------------------------------------------------
  {
    const KID = 'node-emoji-keys-EdDSA';
    const { privateKey, publicJWK } = await generateUCPSigningKey({ kid: KID });
    const profile = buildUCPProfile({
      name: 'Emoji Keys Merchant',
      services: [{ type: 'rest', url: 'https://emoji.example.com' }],
      payment_handlers: [{ name: 'tempo', config: {} }],
      signing_keys: [publicJWK as UCPSigningKey],
      extras: {
        a: 1,
        '豈': 2,
        '': 3,
        '🍷': 4,
      },
    });
    const signed = await signUCPProfile(profile, { signingKey: privateKey, kid: KID });
    writeFixture('node-emoji-keys', {
      profile: signed,
      jwks: buildJWKSResponse([publicJWK]),
      alg: 'EdDSA',
      kid: KID,
      generator: 'node',
    });
  }

  // -------------------------------------------------------------------------
  // node-int-boundary — exercises Number.MAX_SAFE_INTEGER round-trip
  // -------------------------------------------------------------------------
  {
    const KID = 'node-int-boundary-EdDSA';
    const { privateKey, publicJWK } = await generateUCPSigningKey({ kid: KID });
    const profile = buildUCPProfile({
      name: 'Int Boundary Merchant',
      services: [{ type: 'rest', url: 'https://i.example.com' }],
      payment_handlers: [],
      signing_keys: [publicJWK as UCPSigningKey],
      extras: {
        max_safe_int: 9007199254740991,
        min_safe_int: -9007199254740991,
        small_int: 42,
        neg_small_int: -42,
        zero: 0,
      },
    });
    const signed = await signUCPProfile(profile, { signingKey: privateKey, kid: KID });
    writeFixture('node-int-boundary', {
      profile: signed,
      jwks: buildJWKSResponse([publicJWK]),
      alg: 'EdDSA',
      kid: KID,
      generator: 'node',
    });
  }

  // -------------------------------------------------------------------------
  // node-data-driven-claims — exercises the buildUCPProfile data path with
  // API-shape "missing" sentinels (empty string + null). Both languages MUST
  // emit identical canonical bytes for this input.
  // -------------------------------------------------------------------------
  {
    const KID = 'node-data-driven-claims-EdDSA';
    const { privateKey, publicJWK } = await generateUCPSigningKey({ kid: KID });
    const data: AgentScoreData = {
      decision: 'allow',
      decision_reasons: [],
      resolved_operator: 'op_data_driven',
      verify_url: 'https://agentscore.sh/verify/op_data_driven',
      account_verification: {
        kyc_level: '',
        sanctions_clear: false,
        age_bracket: null as unknown as string,
        jurisdiction: null as unknown as string,
        verified_at: null,
      },
    };
    const profile = buildUCPProfile({
      name: 'Data Driven Claims Merchant',
      services: [{ type: 'rest', url: 'https://d.example.com' }],
      payment_handlers: [],
      signing_keys: [publicJWK as UCPSigningKey],
      data,
    });
    const signed = await signUCPProfile(profile, { signingKey: privateKey, kid: KID });
    writeFixture('node-data-driven-claims', {
      profile: signed,
      jwks: buildJWKSResponse([publicJWK]),
      alg: 'EdDSA',
      kid: KID,
      generator: 'node',
    });
  }

  // -------------------------------------------------------------------------
  // node-typed-claims — exercises the typed AssessResult fields (no raw
  // fallback). Cross-lang parity check for the typed-field-only call site.
  // -------------------------------------------------------------------------
  {
    const KID = 'node-typed-claims-EdDSA';
    const { privateKey, publicJWK } = await generateUCPSigningKey({ kid: KID });
    const data: AgentScoreData = {
      decision: 'allow',
      decision_reasons: [],
      resolved_operator: 'op_typed_claims',
      verify_url: 'https://agentscore.sh/verify/op_typed_claims',
      operator_verification: {
        level: 'enhanced',
        operator_type: 'api',
        verified_at: '2026-04-01T00:00:00Z',
      },
      account_verification: {
        kyc_level: 'enhanced',
        sanctions_clear: true,
        age_bracket: '21+',
        jurisdiction: 'US',
        verified_at: '2026-04-01T00:00:00Z',
      },
    };
    const profile = buildUCPProfile({
      name: 'Typed Claims Merchant',
      services: [{ type: 'rest', url: 'https://t.example.com' }],
      payment_handlers: [],
      signing_keys: [publicJWK as UCPSigningKey],
      data,
    });
    const signed = await signUCPProfile(profile, { signingKey: privateKey, kid: KID });
    writeFixture('node-typed-claims', {
      profile: signed,
      jwks: buildJWKSResponse([publicJWK]),
      alg: 'EdDSA',
      kid: KID,
      generator: 'node',
    });
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
