/**
 * Regenerate the full cross-lang fixture corpus (Node side).
 *
 * Writes all `node-*.json` fixtures under `tests/fixtures/cross-lang/`. Used after
 * a canonicalization-relevant change (typ rename, capability-name rename, schema-URL
 * rename, key-sort tweak, profile-shape change) where every JWS in the corpus needs
 * to be re-signed.
 *
 * Each scenario hand-crafts the profile body using the spec-compliant input shape
 * (`services` / `capabilities` / `payment_handlers` as MAPS keyed by reverse-DNS
 * service / capability / handler name), signs with a fresh keypair, and writes the
 * `{ profile, jwks, alg, kid, generator }` envelope. Cross-lang verify in
 * `tests/identity/cross-lang.test.ts` (and the python sibling) pulls these in
 * alongside the `py-*` fixtures generated by the python sibling.
 *
 * Run: `bun run scripts/regenerate-cross-lang-fixtures.ts`
 */

import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import {
  buildUCPProfile,
  type UCPCapabilityBinding,
  type UCPPaymentHandlerBinding,
  type UCPServiceBinding,
  type UCPSigningKey,
} from '../src/identity/ucp';
import {
  buildJWKSResponse,
  generateUCPSigningKey,
  signUCPProfile,
  type SignedUCPProfile,
} from '../src/identity/ucp-jwks';

const OUT_DIR = join(__dirname, '..', 'tests', 'fixtures', 'cross-lang');

interface FixtureEnvelope {
  profile: SignedUCPProfile;
  jwks: { keys: UCPSigningKey[] };
  alg: 'EdDSA' | 'ES256';
  kid: string;
  generator: 'node';
}

function writeFixture(name: string, env: FixtureEnvelope): void {
  const out = join(OUT_DIR, `${name}.json`);
  writeFileSync(out, `${JSON.stringify(env, null, 2)}\n`);
  console.warn(`wrote ${out}`);
}

// Spec-compliant binding helpers — each scenario uses these (or variants) so the
// fixtures cover the full set of canonical UCP fields per binding type.
function shopServiceMcp(host: string): UCPServiceBinding {
  return {
    version: '2026-04-08',
    spec: 'https://ucp.dev/2026-04-08/specification/overview',
    transport: 'mcp',
    endpoint: `${host}/api/ucp/mcp`,
    schema: 'https://ucp.dev/services/shopping/openrpc.json',
  };
}

function shopServiceA2A(host: string): UCPServiceBinding {
  return {
    version: '2026-04-08',
    spec: 'https://ucp.dev/2026-04-08/specification/overview',
    transport: 'a2a',
    endpoint: `${host}/.well-known/agent-card.json`,
  };
}

function tempoHandler(config?: Record<string, unknown>): UCPPaymentHandlerBinding {
  const out: UCPPaymentHandlerBinding = {
    id: 'tempo',
    version: '2026-04-08',
    spec: 'https://agentscore.sh/specification/payment-handlers/tempo',
    schema: 'https://agentscore.sh/schemas/payment-handlers/tempo.json',
  };
  if (config) out.config = config;
  return out;
}

function x402Handler(networks: string[]): UCPPaymentHandlerBinding {
  return {
    id: 'x402',
    version: '2026-04-08',
    spec: 'https://agentscore.sh/specification/payment-handlers/x402',
    schema: 'https://agentscore.sh/schemas/payment-handlers/x402.json',
    config: { networks },
  };
}

function stripeHandler(config: Record<string, unknown>): UCPPaymentHandlerBinding {
  return {
    id: 'stripe',
    version: '2026-04-08',
    spec: 'https://agentscore.sh/specification/payment-handlers/stripe-spt',
    schema: 'https://agentscore.sh/schemas/payment-handlers/stripe-spt.json',
    config,
  };
}

async function main(): Promise<void> {
  // -------------------------------------------------------------------------
  // node-minimal — empty maps; just metadata + signing keys
  // -------------------------------------------------------------------------
  {
    const KID = 'node-minimal-EdDSA';
    const { privateKey, publicJWK } = await generateUCPSigningKey({ kid: KID });
    const profile = buildUCPProfile({
      name: 'Minimal Merchant',
      services: { 'dev.ucp.shopping': [shopServiceMcp('https://m.example.com')] },
      signing_keys: [publicJWK as UCPSigningKey],
    });
    const signed = await signUCPProfile(profile, { signingKey: privateKey, kid: KID });
    writeFixture('node-minimal', {
      profile: signed,
      jwks: buildJWKSResponse([publicJWK]),
      alg: 'EdDSA',
      kid: KID,
      generator: 'node',
    });
  }

  // -------------------------------------------------------------------------
  // node-es256-rails — multi-transport service + multi-rail + ES256 signing key
  // -------------------------------------------------------------------------
  {
    const KID = 'node-es256-rails-ES256';
    const { privateKey, publicJWK } = await generateUCPSigningKey({ kid: KID, alg: 'ES256' });
    const profile = buildUCPProfile({
      name: 'ES256 Merchant',
      services: {
        'dev.ucp.shopping': [
          shopServiceMcp('https://a.example.com'),
          shopServiceA2A('https://a.example.com'),
        ],
      },
      payment_handlers: {
        'sh.agentscore.payment.tempo': [tempoHandler({ rail: 'tempo-mainnet', chain_id: 4217 })],
        'sh.agentscore.payment.x402': [x402Handler(['base-8453'])],
      },
      signing_keys: [publicJWK as UCPSigningKey],
    });
    const signed = await signUCPProfile(profile, { signingKey: privateKey, kid: KID, alg: 'ES256' });
    writeFixture('node-es256-rails', {
      profile: signed,
      jwks: buildJWKSResponse([publicJWK]),
      alg: 'ES256',
      kid: KID,
      generator: 'node',
    });
  }

  // -------------------------------------------------------------------------
  // node-extras-int — payment_handler config with int + string fields
  // -------------------------------------------------------------------------
  {
    const KID = 'node-extras-int-EdDSA';
    const { privateKey, publicJWK } = await generateUCPSigningKey({ kid: KID });
    const profile = buildUCPProfile({
      name: 'Extras Merchant',
      services: { 'dev.ucp.shopping': [shopServiceMcp('https://e.example.com')] },
      payment_handlers: {
        'sh.agentscore.payment.stripe-spt': [stripeHandler({ profile_id: 'abc', count: 7 })],
      },
      signing_keys: [publicJWK as UCPSigningKey],
    });
    const signed = await signUCPProfile(profile, { signingKey: privateKey, kid: KID });
    writeFixture('node-extras-int', {
      profile: signed,
      jwks: buildJWKSResponse([publicJWK]),
      alg: 'EdDSA',
      kid: KID,
      generator: 'node',
    });
  }

  // -------------------------------------------------------------------------
  // node-capability — hand-crafted vendor capability under sh.agentscore.identity
  // -------------------------------------------------------------------------
  {
    const KID = 'node-capability-EdDSA';
    const { privateKey, publicJWK } = await generateUCPSigningKey({ kid: KID });
    const customCapability: UCPCapabilityBinding = {
      version: '1',
      spec: 'https://agentscore.sh/specification/identity',
      schema: 'https://agentscore.sh/schemas/ucp/sh-agentscore-identity-v1.json',
      // `extras` flat on the binding — kyc_required is a vendor field on this binding.
      kyc_required: true,
    };
    const profile = buildUCPProfile({
      name: 'Capability Merchant',
      services: { 'dev.ucp.shopping': [shopServiceMcp('https://c.example.com')] },
      capabilities: { 'sh.agentscore.identity': [customCapability] },
      payment_handlers: {
        'sh.agentscore.payment.tempo': [tempoHandler({ rail: 'tempo-mainnet', chain_id: 4217 })],
      },
      signing_keys: [publicJWK as UCPSigningKey],
    });
    const signed = await signUCPProfile(profile, { signingKey: privateKey, kid: KID });
    writeFixture('node-capability', {
      profile: signed,
      jwks: buildJWKSResponse([publicJWK]),
      alg: 'EdDSA',
      kid: KID,
      generator: 'node',
    });
  }

  // -------------------------------------------------------------------------
  // node-unicode — multi-byte UTF-8 in name / endpoint / config
  // -------------------------------------------------------------------------
  {
    const KID = 'node-unicode-EdDSA';
    const { privateKey, publicJWK } = await generateUCPSigningKey({ kid: KID });
    const profile = buildUCPProfile({
      name: 'Café 日本 🍷 Merchant',
      services: { 'dev.ucp.shopping': [shopServiceMcp('https://日本.example.com')] },
      payment_handlers: {
        'sh.agentscore.payment.tempo': [tempoHandler({ note: 'メモ' })],
      },
      signing_keys: [publicJWK as UCPSigningKey],
    });
    const signed = await signUCPProfile(profile, { signingKey: privateKey, kid: KID });
    writeFixture('node-unicode', {
      profile: signed,
      jwks: buildJWKSResponse([publicJWK]),
      alg: 'EdDSA',
      kid: KID,
      generator: 'node',
    });
  }

  // -------------------------------------------------------------------------
  // node-multikey — JWKS with two keys, signed by the newer one
  // -------------------------------------------------------------------------
  {
    const oldKey = await generateUCPSigningKey({ kid: 'node-multikey-old' });
    const newKey = await generateUCPSigningKey({ kid: 'node-multikey-new' });
    const profile = buildUCPProfile({
      name: 'Multi-Key Merchant',
      services: { 'dev.ucp.shopping': [shopServiceMcp('https://mk.example.com')] },
      payment_handlers: {
        'sh.agentscore.payment.tempo': [tempoHandler({ rail: 'tempo-mainnet' })],
      },
      signing_keys: [oldKey.publicJWK as UCPSigningKey, newKey.publicJWK as UCPSigningKey],
    });
    const signed = await signUCPProfile(profile, { signingKey: newKey.privateKey, kid: 'node-multikey-new' });
    writeFixture('node-multikey', {
      profile: signed,
      jwks: buildJWKSResponse([oldKey.publicJWK, newKey.publicJWK]),
      alg: 'EdDSA',
      kid: 'node-multikey-new',
      generator: 'node',
    });
  }

  // -------------------------------------------------------------------------
  // node-emoji-keys — extras with non-ASCII object keys (BMP private use,
  // CJK compatibility, supplementary plane). Exercises codepoint-vs-UTF-16 sort.
  // Lives at top-level `extras` (outside the `ucp` envelope).
  // -------------------------------------------------------------------------
  {
    const KID = 'node-emoji-keys-EdDSA';
    const { privateKey, publicJWK } = await generateUCPSigningKey({ kid: KID });
    const profile = buildUCPProfile({
      name: 'Emoji Keys Merchant',
      services: { 'dev.ucp.shopping': [shopServiceMcp('https://emoji.example.com')] },
      payment_handlers: {
        'sh.agentscore.payment.tempo': [tempoHandler()],
      },
      signing_keys: [publicJWK as UCPSigningKey],
      extras: {
        a: 1,
        '豈': 2,
        '': 3,
        '🍷': 4,
      },
    });
    const signed = await signUCPProfile(profile, { signingKey: privateKey, kid: KID });
    writeFixture('node-emoji-keys', {
      profile: signed,
      jwks: buildJWKSResponse([publicJWK]),
      alg: 'EdDSA',
      kid: KID,
      generator: 'node',
    });
  }

  // -------------------------------------------------------------------------
  // node-int-boundary — exercises Number.MAX_SAFE_INTEGER round-trip via extras
  // -------------------------------------------------------------------------
  {
    const KID = 'node-int-boundary-EdDSA';
    const { privateKey, publicJWK } = await generateUCPSigningKey({ kid: KID });
    const profile = buildUCPProfile({
      name: 'Int Boundary Merchant',
      services: { 'dev.ucp.shopping': [shopServiceMcp('https://i.example.com')] },
      signing_keys: [publicJWK as UCPSigningKey],
      extras: {
        max_safe_int: 9007199254740991,
        min_safe_int: -9007199254740991,
        small_int: 42,
        neg_small_int: -42,
        zero: 0,
      },
    });
    const signed = await signUCPProfile(profile, { signingKey: privateKey, kid: KID });
    writeFixture('node-int-boundary', {
      profile: signed,
      jwks: buildJWKSResponse([publicJWK]),
      alg: 'EdDSA',
      kid: KID,
      generator: 'node',
    });
  }

  // -------------------------------------------------------------------------
  // node-agentscore-gate-full — exercises buildUCPProfile with a full merchant
  // gate policy declared via `agentscore_gate`. Both languages MUST emit
  // identical canonical bytes so a profile signed in one verifies in the other.
  // -------------------------------------------------------------------------
  {
    const KID = 'node-agentscore-gate-full-EdDSA';
    const { privateKey, publicJWK } = await generateUCPSigningKey({ kid: KID });
    const profile = buildUCPProfile({
      name: 'AgentScore Gate Full-Policy Merchant',
      services: { 'dev.ucp.shopping': [shopServiceMcp('https://d.example.com')] },
      signing_keys: [publicJWK as UCPSigningKey],
      agentscore_gate: {
        require_kyc: true,
        require_sanctions_clear: true,
        min_age: 21,
        allowed_jurisdictions: ['US'],
      },
    });
    const signed = await signUCPProfile(profile, { signingKey: privateKey, kid: KID });
    writeFixture('node-agentscore-gate-full', {
      profile: signed,
      jwks: buildJWKSResponse([publicJWK]),
      alg: 'EdDSA',
      kid: KID,
      generator: 'node',
    });
  }

  // -------------------------------------------------------------------------
  // node-agentscore-gate-blocked — exercises blocked_jurisdictions
  // (mutually exclusive with allowed_jurisdictions) for cross-lang parity.
  // -------------------------------------------------------------------------
  {
    const KID = 'node-agentscore-gate-blocked-EdDSA';
    const { privateKey, publicJWK } = await generateUCPSigningKey({ kid: KID });
    const profile = buildUCPProfile({
      name: 'AgentScore Gate Blocked-Jurisdictions Merchant',
      services: { 'dev.ucp.shopping': [shopServiceMcp('https://t.example.com')] },
      signing_keys: [publicJWK as UCPSigningKey],
      agentscore_gate: {
        require_kyc: true,
        blocked_jurisdictions: ['KP', 'IR', 'CU'],
      },
    });
    const signed = await signUCPProfile(profile, { signingKey: privateKey, kid: KID });
    writeFixture('node-agentscore-gate-blocked', {
      profile: signed,
      jwks: buildJWKSResponse([publicJWK]),
      alg: 'EdDSA',
      kid: KID,
      generator: 'node',
    });
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
